spring.application.name=ticket-arena

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.url=${DB_URL}

management.endpoint.health.show-details=always