CREATE TABLE seats
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id  BIGINT      NOT NULL REFERENCES sections (id) ON DELETE CASCADE,
    row_label   VARCHAR(10) NOT NULL,
    seat_number INT         NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (section_id, row_label, seat_number)
);

CREATE INDEX idx_seats_section_id ON seats (section_id);