CREATE TABLE venues
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150) NOT NULL,
    country        VARCHAR(40)  NOT NULL,
    city           VARCHAR(40)  NOT NULL,
    address        VARCHAR(40)  NOT NULL,
    total_capacity INTEGER      NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);