CREATE TABLE tickets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id     UUID UNIQUE    NOT NULL,
    booking_id    BIGINT         NOT NULL REFERENCES bookings (id) ON DELETE RESTRICT,
    event_seat_id BIGINT         NOT NULL REFERENCES event_seats (id) ON DELETE RESTRICT,
    price_paid    NUMERIC(10, 2) NOT NULL CHECK ( price_paid >= 0 ),
    seat_label    VARCHAR(50)    NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ
);

CREATE INDEX idx_tickets_booking_id ON tickets (booking_id);
CREATE INDEX idx_tickets_event_seat_id ON tickets (event_seat_id);
