CREATE TABLE sections
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id      BIGINT      NOT NULL REFERENCES venues (id) ON DELETE CASCADE,
    name          VARCHAR(30) NOT NULL,
    display_order INTEGER     NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sections_venue_id ON sections (venue_id);